import { Filament, FilamentType, SpecialColor } from './filament';

export const DUMMY_FILAMENTS: Filament[] = [
  {
    id: 'fil-pc-black',
    title: 'Black PC',
    brand: 'Prusament',
    colors: ['#000000'],
    types: ['matte'],
    href: 'https://example.com/pc-black',
    pricePerKilo: 29.99,
    numSpoolsOwned: 2,
    totalUsed: 0.4,
  },
  {
    id: 'fil-pla-silk-gold',
    title: 'Silk Gold PLA',
    brand: 'Overture',
    colors: ['#D4AF37'],
    types: ['silk'],
    href: 'https://example.com/pla-silk-gold',
    pricePerKilo: 22.5,
    numSpoolsOwned: 1,
    totalUsed: 0.15,
  },
  {
    id: 'fil-pla-speed-white',
    title: 'Speed White PLA+',
    brand: 'eSun',
    colors: ['#FFFFFF'],
    types: ['speed'],
    href: 'https://example.com/pla-speed-white',
    pricePerKilo: 19.99,
    numSpoolsOwned: 3,
    totalUsed: 1.0,
  },
  {
    id: 'fil-pla-matte-black',
    title: 'Matte Black PLA',
    brand: 'Generic',
    colors: ['#111111'],
    types: ['matte'],
    href: 'https://example.com/pla-matte-black',
    pricePerKilo: 21.0,
    numSpoolsOwned: 1,
    totalUsed: 0.05,
  },
  {
    id: 'fil-pla-matte-cyan',
    title: 'Matte Cyan PLA',
    brand: 'Generic',
    colors: ['#22CCEE'],
    types: ['matte'],
    href: 'https://example.com/pla-matte-cyan',
    pricePerKilo: 21.0,
    numSpoolsOwned: 1,
    totalUsed: 0.08,
  },
  {
    id: 'fil-pla-dual-blue-green',
    title: 'Dual Blue/Green PLA',
    brand: 'Hatchbox',
    colors: ['#1E90FF', '#00C853'],
    types: ['multicolor'],
    href: 'https://example.com/pla-dual-blue-green',
    pricePerKilo: 24.0,
    numSpoolsOwned: 1,
    totalUsed: 0.25,
  },
  {
    id: 'fil-pla-tricolor',
    title: 'Tri-Color PLA',
    brand: 'SUNLU',
    colors: ['#FF6B6B', '#FFD93D', '#6BCB77'],
    types: ['multicolor'],
    href: 'https://example.com/pla-tricolor',
    pricePerKilo: 25.0,
    numSpoolsOwned: 0,
    totalUsed: 0.0,
  },
  {
    id: 'fil-pla-rainbow',
    title: 'Rainbow PLA',
    brand: 'GizmoDorks',
    colors: [SpecialColor.Rainbow],
    types: ['multicolor'],
    href: 'https://example.com/pla-rainbow',
    pricePerKilo: 27.0,
    numSpoolsOwned: 1,
    totalUsed: 0.6,
  },
];


